### ISSUE TITLE
Update for 3.1.1 support

### ISSUE THREAD

**Issue by axcr** [ai/jquery-cdn#6]
The latest jQuery Version on Google Cloud is 3.1.1. i think, a update is necessary to support such version.

**Comment by ai** [comment]
I don’t see future in Rails Sprockets and jQuery. So this module is depreacted and I will support only 1.x and 2.x updates.

Do you want to maintain this project and start 3.x branch?

**Comment by lulalala** [comment]
@ai would be nice if you can mention about deprecation in readme?

**Comment by ai** [comment]
I deprecated the project
